server:
    port: 8080
    servlet:
        context-path: /testspring

spring:
    datasource:
        url: ${DB_CONNECTION}
        driver-class-name: "com.mysql.cj.jdbc.Driver"
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

# Đây là các biến dùng trên môi trường dev
jwt:
    signer-key: "bb735f68774cd060f548b25006931af8965acf3b4f0967685f72ebf7c0701998"
    access-token-validity-in-seconds: 3600
    refreshable-duration-in-seconds: 360000

app:
    init:
        admin:
            username: admin
            password: ${INIT_ADMIN_PASSWORD}